[global_tags]
  realm = '${var.region}'
  role = 'nomad'
[agent]
[[outputs.prometheus_client]]
  listen = ':9273'
[[inputs.cpu]]
  percpu = true
  totalcpu = true
[[inputs.disk]]
  ignore_fs = ['tmpfs', 'devtmpfs']
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.net]]
[[inputs.ntpq]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]